# options
set -g default-terminal "tmux-256color"
set -sa terminal-features ',foot:RGB'
set -g detach-on-destroy off
set -g mouse on
set -g base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g status-position top

# bindings
set -g prefix C-s
bind C-s send-prefix
bind -n C-h send-keys C-w
bind r source-file ~/.config/tmux/tmux.conf
bind H previous-window
bind L next-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# theme
set -g @catppuccin_flavour "mocha"
set -g @catppuccin_window_status_style "rounded"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'omerxx/catppuccin-tmux'
set -g @plugin 'omerxx/tmux-sessionx'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
