# man fnott.ini
anchor=top-right
background=1e1e2eff
default-timeout=5
idle-timeout=60

body-color=cdd6f4ff
body-font=JetBrainsMono Nerd Font:size=12
body-format=%b

border-color=89b4faee
border-radius=8
border-size=2

edge-margin-horizontal=31
edge-margin-vertical=35

icon-theme=Papirus
max-icon-size=32

layer=overlay

notification-margin=10

padding-horizontal=15
padding-vertical=10

selection-helper-uses-null-separator=yes
selection-helper=fuzzel --dmenu0

summary-color=89b4faff
summary-font=JetBrainsMono Nerd Font:weight=Bold:size=13
summary-format=%s

title-color=ffffffff
title-font=JetBrainsMono Nerd Font:size=10
title-format=

max-width=500
