return {}
-- return {
--   'ThePrimeagen/harpoon',
--   branch = 'harpoon2',
--   dependencies = { 'nvim-lua/plenary.nvim' },
--   keys = {
--     { "<leader>j", desc = "Harpoon" },
--     { "<A-S-J>", function() require("harpoon"):list():select(1) end, desc = "Select mark 1" },
--     { "<A-S-K>", function() require("harpoon"):list():select(2) end, desc = "Select mark 2" },
--     { "<A-S-L>", function() require("harpoon"):list():select(3) end, desc = "Select mark 3" },
--     { "<A-S-:>", function() require("harpoon"):list():select(4) end, desc = "Select mark 4" },
--     { "<leader>jf", function() require("harpoon"):list():add() end, desc = "Add file" },
--     {
--       "<leader>jd",
--       function() require("harpoon").ui:toggle_quick_menu(require("harpoon"):list()) end,
--       desc = "Toggle quick menu"
--     },
--     {
--       "<leader>js",
--       function()
--         vim.ui.input({ prompt = "Harpoon mark index: " }, function(input)
--           local num = tonumber(input)
--           if num then require("harpoon"):list():select(num) end
--         end)
--       end,
--       desc = "Goto index of mark",
--     },
--     { "<leader>jj", function() require("harpoon"):list():prev() end, desc = "Goto previous mark" },
--     { "<leader>jk", function() require("harpoon"):list():next() end, desc = "Goto next mark" },
--   },
-- }
