[wezterm.files]
"wezterm" = "~/.config/wezterm"

[clink.files]
"clink/clink.lua" = "~/AppData/Local/clink/clink.lua"
"clink/starship.lua" = "~/AppData/Local/clink/starship.lua"
"clink/aliases.lua" = "~/AppData/Local/clink/aliases.lua"
"clink/zoxide.lua" = "~/AppData/Local/clink/zoxide.lua"

[nvim.files]
"nvim" =  "~/AppData/Local/nvim"
"nvim/assets/presence/jmc.png" = { target = "~/AppData/Local/nvim/assets/presence/jmc.png", type = "symbolic" }
"nvim/assets/presence/mcfunction.png" = { target = "~/AppData/Local/nvim/assets/presence/mcfunction.png", type = "symbolic" }

[kanata.files]
"kanata/kanata.kbd" = "d:/amandin/customization/kanata/kanata.kbd"
"kanata/kanata-tray.toml" = "~/AppData/Roaming/kanata-tray/kanata-tray.toml"

[fastfetch.files]
"fastfetch/config.jsonc" = { target = "~/.config/fastfetch/config.jsonc", type = "template" }
"fastfetch/windows.txt" = { target = "~/.config/fastfetch/windows.txt", type = "template" }
