[wezterm.files]
wezterm = "~/.config/wezterm"

[clink.files]
clink = "~/AppData/Local/clink"

[nvim.files]
nvim = "~/AppData/Local/nvim"
"nvim/assets/presence/jmc.png" = { target = "~/AppData/Local/nvim/assets/presence/jmc.png", type = "symbolic" }
"nvim/assets/presence/mcfunction.png" = { target = "~/AppData/Local/nvim/assets/presence/mcfunction.png", type = "symbolic" }

[kanata.files]
"kanata/kanata.kbd" = "d:/amandin/customization/kanata/kanata.kbd"
"kanata/kanata-tray.toml" = "~/AppData/Roaming/kanata-tray/kanata-tray.toml"

[fastfetch.files]
fastfetch = "~/.config/fastfetch"

[iamb.files]
"iamb/config.toml" = "~/AppData/Roaming/iamb/config.toml"
