config_version = 8

[audio]
enable_sounds = true

[bar.default]
capsule = true
margin_ends = 0
position = "right"
start = [ "workspaces", "taskbar" ]

    [bar.default.dead_zone.actions]
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

[brightness]
enable_ddcutil = true

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
reserve_space = false

[location]
auto_locate = true

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 229.0
    box_width = 810.0
    cx = 960.0
    cy = 881.5
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[osd]
position_vertical = "bottom_right"

[plugins]
enabled = [ "noctalia/translator", "noctalia/wallhaven", "radimous/prismlauncher-instances", "icefish/phone-connect" ]

[shell]
clipboard_auto_paste = "off"
font_family = "Inter"

    [shell.launcher]
    auto_paste = "off"
    compact = false

    [shell.panel]
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Lavender"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt" ]
    community_ids = [ "prismlauncher" ]

[wallpaper]
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/amandin/Downloads/wallpaper/wallhaven-6lylmw.png"

    [wallpaper.last]
    path = "/home/amandin/Downloads/wallpaper/wallhaven-6lylmw.png"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/amandin/Downloads/wallpaper/wallhaven-6lylmw.png"

[widget.date]
format = "{:%d}"

[widget.lock_keys]
color = "shadow"
icon_color = "secondary"

[widget.taskbar]
only_active_workspace = true

[widget.workspaces]
display = "none"
focused_color = "primary"
hide_when_empty = true